### ISSUE TITLE
documentation understanding problem

### ISSUE THREAD

**Issue by ghost** [dambrisco/swiss-pairing#2]
can you help to understand the **matches** object ? do I need to pass home away pair ? how make that pair ?
```
[
  {
    'round': match_round,
    'home': {
      'id': home_participant_id,
      'points': home_won_points
    },
    'home': {
      'id': away_participant_id,
      'points': away_won_points
    }
  }
]
```

**Comment by dambrisco** [comment]
There was a minor error there in the README, it's been updated to the object below:

```
[
  {
    'round': match_round,
    'home': {
      'id': home_participant_id,
      'points': home_won_points
    },
    'away': {
      'id': away_participant_id,
      'points': away_won_points
    }
  }
]
```

You *will* need to create this array from your match history because without it any matchups generated will simply be representative of the initial round.

An example object might look like the following:
```
{
  'round': 1,
  'home': {
    'id': 'Raul',
    'points': 1
  },
  'away': {
    'id': 'Andy',
    'points': 0
  }
```
And you'd have multiple objects like this to describe your first round in order to determine matchups for the second round.

**Comment by ghost** [comment]
thank you very much for your module, it's very helpful, but I have a question: Does it make sorting by points ? It gives me the result, where players with more points are in the middle of table

**Comment by dambrisco** [comment]
Which function are you calling that you expect sorted results for? It's definitely possible that you might need to sort the results yourself.

**Comment by ghost** [comment]
yes, you are right. thanks
